/**
 * Automatic Crash & Error Reporter for AitherShell.
 *
 * Catches uncaught exceptions and unhandled rejections, prompts the user
 * to submit an error report, and creates a GitHub issue via Genesis API.
 *
 * Flow:
 *   1. Error caught → format crash report
 *   2. Prompt user: "Send error report? (Y/n)"
 *   3. POST to Genesis /feedback → Genesis creates GitHub issue
 *   4. Show issue URL or fallback support link
 */

import { createInterface } from 'node:readline';
import { execSync } from 'node:child_process';
import { hostname, platform, release, arch, cpus, totalmem } from 'node:os';
import chalk from 'chalk';
import { VERSION as SHELL_VERSION } from './version.js';

const GENESIS_URL = process.env.AITHER_GENESIS_URL || 'http://localhost:8001';
const GITHUB_REPO = 'Aitherium/AitherOS';
const SUPPORT_URL = 'https://demo.aitherium.com/support';
const VERSION = SHELL_VERSION;

interface CrashReport {
  title: string;
  error_type: string;
  message: string;
  stack: string;
  context: {
    command?: string;
    version: string;
    platform: string;
    arch: string;
    os_release: string;
    node_version: string;
    hostname: string;
    ram_gb: number;
    cpu: string;
    gpu?: string;
    timestamp: string;
  };
}

/** Currently executing command (set by REPL/main before each command). */
let _currentCommand = '';

/** Set the current command context for crash reports. */
export function setCurrentCommand(cmd: string): void {
  _currentCommand = cmd;
}

/**
 * When the blessed full-screen TUI owns the terminal, the crash reporter must
 * NOT draw to stdout or prompt on stdin (it would corrupt the screen / steal
 * keystrokes). The TUI registers a teardown callback here; on a real uncaught
 * crash we restore the terminal first, then report on the clean terminal.
 */
let _tuiTeardown: (() => void) | null = null;

/** Mark the TUI active (pass its destroy fn) or inactive (pass null). */
export function setTuiActive(teardown: (() => void) | null): void {
  _tuiTeardown = teardown;
}

/** Detect GPU (best-effort, non-blocking). */
function detectGpu(): string | undefined {
  try {
    const out = execSync('nvidia-smi --query-gpu=name,memory.total --format=csv,noheader', {
      timeout: 3000,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).toString().trim();
    return out || undefined;
  } catch {
    return undefined;
  }
}

/** Build a structured crash report from an error. */
function buildReport(error: Error | any, source: string): CrashReport {
  const err = error instanceof Error ? error : new Error(String(error));
  const title = `[AitherShell Crash] ${err.message?.slice(0, 120) || 'Unknown error'}`;

  return {
    title,
    error_type: err.constructor?.name || 'Error',
    message: err.message || String(error),
    stack: err.stack || 'No stack trace',
    context: {
      command: _currentCommand || undefined,
      version: VERSION,
      platform: platform(),
      arch: arch(),
      os_release: release(),
      node_version: process.version,
      hostname: hostname(),
      ram_gb: Math.round(totalmem() / (1024 ** 3)),
      cpu: cpus()[0]?.model || 'unknown',
      gpu: detectGpu(),
      timestamp: new Date().toISOString(),
    },
  };
}

/** Format the crash report as a GitHub issue body (Markdown). */
function formatIssueBody(report: CrashReport): string {
  const ctx = report.context;
  return `## Automatic Error Report

**Source**: AitherShell CLI v${ctx.version}
**Timestamp**: ${ctx.timestamp}
${ctx.command ? `**Command**: \`${ctx.command}\`` : ''}

### Error
\`\`\`
${report.error_type}: ${report.message}
\`\`\`

### Stack Trace
\`\`\`
${report.stack}
\`\`\`

### Environment
| Field | Value |
|-------|-------|
| Platform | ${ctx.platform} ${ctx.arch} |
| OS | ${ctx.os_release} |
| Node | ${ctx.node_version} |
| RAM | ${ctx.ram_gb} GB |
| CPU | ${ctx.cpu} |
${ctx.gpu ? `| GPU | ${ctx.gpu} |` : '| GPU | None detected |'}

---
*Auto-generated by AitherShell crash reporter*`;
}

/** Ask user Y/n with a default of Y. */
async function askConfirm(prompt: string): Promise<boolean> {
  // If stdin is not a TTY (piped input), default to yes
  if (!process.stdin.isTTY) return true;

  const rl = createInterface({ input: process.stdin, output: process.stderr });
  return new Promise<boolean>((resolve) => {
    rl.question(prompt, (answer) => {
      rl.close();
      const a = answer.trim().toLowerCase();
      resolve(a === '' || a === 'y' || a === 'yes');
    });
  });
}

/** Submit crash report via Genesis /feedback endpoint. */
async function submitViaGenesis(report: CrashReport): Promise<string | null> {
  try {
    const resp = await fetch(`${GENESIS_URL}/feedback`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        rating: -1,
        comment: formatIssueBody(report),
        category: 'Bug',
        metadata: {
          source: 'aithershell-crash-reporter',
          type: 'crash_report',
          severity: 'high',
          error_type: report.error_type,
          title: report.title,
          stack_preview: report.stack.split('\n').slice(0, 3).join('\n'),
          platform: report.context.platform,
          version: report.context.version,
          auto_report: true,
        },
      }),
      signal: AbortSignal.timeout(10000),
    });

    if (resp.ok) {
      const data = await resp.json() as any;
      return data?.feedback_id || 'submitted';
    }
    return null;
  } catch {
    return null;
  }
}

/** Try to create a GitHub issue directly via `gh` CLI (fallback). */
function submitViaGhCli(report: CrashReport): string | null {
  try {
    const body = formatIssueBody(report);
    const result = execSync(
      `gh issue create --repo ${GITHUB_REPO} --title "${report.title.replace(/"/g, '\\"')}" --label "bug,auto-report" --body -`,
      {
        input: body,
        timeout: 15000,
        stdio: ['pipe', 'pipe', 'pipe'],
      },
    ).toString().trim();
    // gh returns the issue URL
    return result;
  } catch {
    return null;
  }
}

/** Main crash handler — called on uncaught errors. */
async function handleCrash(error: Error | any, source: string): Promise<void> {
  const report = buildReport(error, source);

  console.error('');
  console.error(chalk.red.bold('  AitherShell encountered an error'));
  console.error(chalk.red(`  ${report.error_type}: ${report.message}`));
  if (_currentCommand) {
    console.error(chalk.dim(`  Command: ${_currentCommand}`));
  }
  console.error('');

  const shouldSend = await askConfirm(
    chalk.yellow('  Send error report to help us fix this? (Y/n) '),
  );

  if (!shouldSend) {
    console.error(chalk.dim('  No report sent. You can submit manually at:'));
    console.error(chalk.cyan(`  ${SUPPORT_URL}`));
    console.error('');
    return;
  }

  // Try Genesis first, then gh CLI fallback
  console.error(chalk.dim('  Submitting error report...'));
  let result = await submitViaGenesis(report);

  if (result) {
    console.error(chalk.green(`  Error report submitted (${result}).`));
    console.error(chalk.dim('  Our team will investigate. Track at:'));
    console.error(chalk.cyan(`  ${SUPPORT_URL}`));
  } else {
    // Fallback: try gh CLI
    const issueUrl = submitViaGhCli(report);
    if (issueUrl) {
      console.error(chalk.green(`  GitHub issue created: ${issueUrl}`));
    } else {
      console.error(chalk.yellow('  Could not submit automatically.'));
      console.error(chalk.dim('  Please report at:'));
      console.error(chalk.cyan(`  ${SUPPORT_URL}`));
    }
  }
  console.error('');
}

/**
 * Install global error handlers. Call once at startup.
 *
 * Catches:
 * - Uncaught exceptions (synchronous throws)
 * - Unhandled promise rejections (async throws)
 */
/** Benign aborts (request cancelled, AbortSignal.timeout orphans) — never fatal. */
function isBenignAbort(err: any): boolean {
  return err?.name === 'AbortError' || err?.code === 'ABORT_ERR'
    || err?.name === 'TimeoutError';
}

export function installCrashReporter(): void {
  process.on('uncaughtException', async (error) => {
    if (isBenignAbort(error)) return;  // orphaned fetch/timer abort — ignore
    // Restore the terminal before drawing the report (no-op outside the TUI).
    if (_tuiTeardown) { try { _tuiTeardown(); } catch { /* */ } _tuiTeardown = null; }
    await handleCrash(error, 'uncaughtException');
    process.exit(1);
  });

  // Unhandled rejections must NOT tear the process down. In the blessed TUI a
  // stray async rejection during a long turn (e.g. an orphaned AbortSignal.timeout
  // surfacing in the silent gap of a grounded follow-up) would otherwise hit
  // process.exit(1) and kill the whole session mid-render. Report-but-survive.
  process.on('unhandledRejection', async (reason) => {
    const error = reason instanceof Error ? reason : new Error(String(reason));
    if (isBenignAbort(error)) return;
    // While the TUI owns the terminal, never draw/prompt over it — submit the
    // report silently and keep the session alive.
    if (_tuiTeardown) {
      try { await submitViaGenesis(buildReport(error, 'unhandledRejection')); } catch { /* */ }
      return;
    }
    try { await handleCrash(error, 'unhandledRejection'); } catch { /* */ }
    // Intentionally do NOT process.exit — keep the session alive.
  });
}

/**
 * Wrap an async function with crash reporting.
 * On error, prompts to send report before re-throwing.
 */
export async function withCrashReporting<T>(
  fn: () => Promise<T>,
  command?: string,
): Promise<T> {
  if (command) setCurrentCommand(command);
  try {
    return await fn();
  } catch (error) {
    await handleCrash(error, 'command');
    throw error;
  }
}
